### ISSUE TITLE
Add nuget target for 1.1

### ISSUE THREAD

**Issue by Banashek** [dustinmoris/Suave.AspNetCore#3]
Hey I was trying to use the library in an application targeting 1.1 with the msbuild tools, but I see that there isn't currently a supported nuget target.

Would it be possible to add the target? I don't think the code would need to change.

**Comment by Banashek** [comment]
Woops my mistake I used the wrong nuget version number =$

**Comment by dustinmoris** [comment]
Cool glad you got it resolved ;) Let me know if you encounter any other issue!
